id: I71455114
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T01:55:31+00:00'
last_modified: '2022-06-08T00:59:41.358548+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25710
  title: སྲིད་གཞུང་གི་ལས་དོན་སྙན་ཞུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A7D7:
      image_group_id: I1KG25712
      title: ''
      total_pages: 73
      order: 1
      base_file: A7D7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
