id: P004434
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25710
  title: སྲིད་གཞུང་གི་ལས་དོན་སྙན་ཞུ།
  author: ''
  volumes:
    b598edb99471497aa4b4c598c9a66126:
      image_group_id: I1KG25712
      title: ''
      volume_number: 1
      total_pages: 73
      base_file: v001.txt
